export const LOAD_GAME_LAYOUT_SUCCESS = 'LOAD_GAME_LAYOUT_SUCCESS';
export const UPDATE_GAME_STATUS = 'UPDATE_GAME_STATUS';
export const INIT_GAME_STATUS_SUCCESS = 'INIT_GAME_STATUS_SUCCESS';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
