export const UPDATE_GAME_STATUS = 'UPDATE_GAME_STATUS';
export const DELETE_GAME_STATUS = 'DELETE_GAME_STATUS';
export const CLEAN_GAME_STATUS = 'CLEAN_GAME_STATUS';
export const GET_GAME_STATUS_SUCCESS = 'INIT_GAME_STATUS_SUCCESS';

export const INIT_AUTH_STATUS = 'INIT_AUTH_STATUS';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const RESET_GAME = 'RESET_GAME';

export const GET_CURRENT_PLAYERS = 'GET_CURRENT_PLAYERS';
export const GET_ACTIVE_PLAYER = 'GET_ACTIVE_PLAYER';
